### ISSUE TITLE
CPF em formato errado

### ISSUE THREAD

**Issue by MatheusFaria** [MatheusFaria/SisRES#6]
A classe cliente só aceita o CPF sem caracteres especias.

**Comment by MatheusFaria** [comment]
Tentarei utilizar a regex: "[\d]{3,3}.[\d]{3,3}.[\d]{3,3}-[\d]{2,2}$"

**Comment by ghost** [comment]
Reacrescentei a classe Util. Usar caracteres especiais estava dando erro. Sempre retornava cpf invalido
