### ISSUE TITLE
Cadastrar

### ISSUE THREAD

**Issue by ghost** [MatheusFaria/SisRES#8]
O Cadastro só diz que já existe alguem cadastrado se TODOS os campos forem iguais.
Isso permite o mesmo cpf ou a mesma matricula para mais de uma pessoa.

![image](https://f.cloud.github.com/assets/2914334/27288/922e75e8-4b7f-11e2-8845-e4cd3cd3e645.png)

**Comment by aulusdiniz** [comment]
é preciso modificar a tabela no banco. o cpf deve ser unique key, assim ao tentar cadastrar, o banco avisa a falhar e o java deve falhar tbm..
